### ISSUE TITLE
 k8s schema validation error: could not find schema for CustomResourceDefinition

### ISSUE THREAD

**Issue by cconnert** [datreeio/datree#538] opened 2022-03-30 11:13 UTC
**Describe the bug**
Running a validation on resources which contain CRDs fail with:

k8s schema validation error: could not find schema for CustomResourceDefinition
You can skip files with missing schemas instead of failing by using the `--ignore-missing-schemas` flag

**To Reproduce**
1. Run command 'wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.2/controller.yaml && datree test --schema-version 1.18.0 controller.yaml '
2. See error during output

**Expected behavior**
That the CRD(s) are validated against their schema correctly

**Desktop (please complete the following information):**
 - OS: Windows/WSL2/Docker

**Datree version (run `datree version`):**
 - Version: 1.1.6

**Additional context**  
If possible, include a YAML file to reproduce the bug.

**Comment by eyarz** [comment] 2022-03-30 12:59
I'm also able to reproduce it.
It looks like an [issue](https://github.com/yannh/kubeconform/issues/100) with kubeconform (it's the package that we're to perform the schema validation).

Until it will get fixed, you can ignore the CRD schema validation (for now) by passing the flag ` --ignore-missing-schemas` to datree: `wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.2/controller.yaml && datree test --schema-version 1.18.0 controller.yaml --ignore-missing-schemas`

**Comment by eyarz** [comment] 2022-03-30 13:38
Just thought about a good workaround that will not require you to skip the CRD schema validation - you can use the `--schema-location` flag and pass the (remote) CRD schema separately:

`wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.2/controller.yaml && datree test --schema-version 1.18.0 controller.yaml --schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.18.0/customresourcedefinition-apiextensions-v1.json`

<img width="902" alt="image" src="https://user-images.githubusercontent.com/19731161/160848048-1db67379-b437-453f-b93f-23a28954bff1.png">

**Comment by eyarz** [comment] 2022-04-07 06:22
The fix for this bug should be done on the Kubeconform project.
Therefore, I'll close this issue as `won't fix`.
I believe that someone from the community will pick it up quickly.

**Comment by royhadad** [comment] 2022-04-13 08:55
will be fixed soon in https://github.com/datreeio/datree/issues/570

**Closed as completed** 2022-04-13 09:47 UTC
Labels: bug
