### ISSUE TITLE
datree requires policy-as-code mode to be enabled even in offline mode

### ISSUE THREAD

**Issue by raphaelehret** [datreeio/datree#642] opened 2022-05-24 14:28 UTC
When running tests in offline mode with a policy file specified, datree still asks to be logged in and have policy-as-code mode enabled, which conflicts with the offline mode use-case

**Steps to reproduce the behavior:**
Activate offline mode, then try to run a test with policy config specified
```
datree config set offline local
datree test file.yaml --policy-config ./policies.yaml
```

**Expected behavior**
Test runs with policies specifed in the `policies.yaml` file, as specified in [the documentation](https://hub.datree.io/setup/offline-mode)

**Actual behavior**
Command fails with the following error: 
```
to use --policy-config flag you must first enable policy-as-code mode: https://hub.datree.io/policy-as-code
```
as if it was still trying to run in online mode

**Desktop (please complete the following information):**
I tried with both 
- Mac
- Debian

**Datree version (run `datree version`):**
I tried with both 
- Version: 1.4.28
 - Version: 1.4.29-rc

**Client ID (`cat ~/.datree/config.yaml`):**
client_id: TeasQHTr6uJQHU8pqPyUUD
offline: local
token:  XXX

**Comment by eyarz** [comment] 2022-05-24 14:52
I'm not able to reproduce the bug :/
![image](https://user-images.githubusercontent.com/19731161/170065064-e36312e9-b062-4517-b166-eb76e07db8a0.png)

if you enable policy as code mode from your dashboard and run this:
```
datree test file.yaml --policy-config ./policies.yaml
```
will datree perform the schema validation check?
![image](https://user-images.githubusercontent.com/19731161/170065750-1b294101-30af-4d2e-809f-19ae1e363cab.png)

**Comment by raphaelehret** [comment] 2022-05-25 07:37
> if you enable policy as code mode from your dashboard and run this:
``` 
datree test file.yaml --policy-config ./policies.yaml
```
> will datree perform the schema validation check?

Yes, it does work, and I also figured out another behavior. 
If I try offline mode **with my internet disabled**, datree will use my local policy. However if I try offline mode **with my internet enabled**, datree will ask for polices-as-code to be enabled. 

So as of right now, offline mode isn't actually offline unless you have your internet disabled. Is this desired behavior? From my understanding, offline-mode should be offline regardless of my connectivity status

**Comment by eyarz** [comment] 2022-05-25 08:23
@raphaelehret this is actually the expected behavior.
may I ask what is the use case that you have that requires you to run datree in offline mode although you have an internet connection?

**Comment by raphaelehret** [comment] 2022-05-25 10:02
We want to locally manage our policy files on our gitlab repository, as we do with pretty much all the configuration we use for our CIs, builds, etc. 

As such, we would like to use the `--policy-config` option to use local policies files, and didn't see a point on "logging in" to your backend when we are not using any of its functionnalities. We try to limit our outgoing traffic as much as possible, and offline mode sounded like the answer to this.

As a side note, I think it would be worth mentionning in the offline mode documentation that this is the expected behavior.

**Comment by eyarz** [comment] 2022-05-25 11:14
interesting.
take in mind that if you're using the offline mode, you will lose a lot of capabilities like schema validation, new built-in policies, and more...

> As such, we would like to use the --policy-config option to use local policies files

is there a specific reason that you prefer to use the `--policy-config` flag over pulling your policy from your centralized policy registry (aka dashboard)?

> We try to limit our outgoing traffic as much as possible, and offline mode sounded like the answer to this.

in this case, you can also use the `--no-record` flag.
this way, you will enjoy the majority of capabilities (schema validation, token management, etc.) w/o sending traffic out :)

> As a side note, I think it would be worth mentionning in the offline mode documentation that this is the expected behavior.

I agree. We only published this doc 3 days so there are still some left-overs (like this) to fix.

**Comment by raphaelehret** [comment] 2022-05-25 11:55
> is there a specific reason that you prefer to use the --policy-config flag over pulling your policy from your centralized policy registry (aka dashboard)?

Yes, we wish to manage and keep our configurations locally, just as we do with other configurations. I understand that we could publish it to the centralized repo, but we would really rather host it ourselves and only rely on our infrastructure

We understand the restrictions offline mode brings, and would still like to use it.
If you don't intend to change the behavior, feel free to close this issue, we will work around it ! 🙂

**Comment by eyarz** [comment] 2022-05-25 12:19
when we designed this feature, we were not aware of this use case because the users that helped us define this were all working in air-gapped environments 😅

this behavior can be changed in the future, but I think the best workaround for your use case will be the enable the policy-as-code mode (once) and use the `--no-record` flag. 

I will go ahead and close this issue.

**Closed as completed by eyarz** 2022-05-25 12:19 UTC
Labels: bug
