### ISSUE TITLE
Showing "Bad Cpu type in executable" error while trying to run Datree

### ISSUE THREAD

**Issue by Abhra303** [datreeio/datree#384] opened 2022-01-18 07:11 UTC
**Describe the bug**
As the #304 is closed now, I tried to install Datree on my Mac M1 machine using curl. The installation was successful but when I tried to run `datree test <yaml_file_path>` it showed the following error - 
```
zsh: bad CPU type in executable: datree
```
It is not just for `test` command only, I cannot run any command like `datree --help`, `datree version` etc. It is showing the same error.

**To Reproduce**
1. On Mac M1, run `curl https://get.datree.io | /bin/bash`
2. When the installation is done, try to run any Datree command
3. See error

**Expected behaviour **
It should run successfully.

**Screenshots**

<img width="560" alt="Screenshot 2022-01-18 at 12 18 23 PM" src="https://user-images.githubusercontent.com/75240995/149885273-36c0985b-02c6-4f9a-b2a8-dd4b7e226c14.png">

**Desktop (please complete the following information):**
 - OS: Mac M1

**Datree version (run `datree version`):**
 - Version: I was not able to run `datree version` but I think the curl command downloaded the latest version i.e. "0.15.0"

**Additional context**  
This [discussion](https://apple.stackexchange.com/questions/408375/zsh-bad-cpu-type-in-executable) suggested to install "Rosetta". So, I think with that I can run it successfully. I have not tried it yet.

**Comment by dimabru** [comment] 2022-01-18 07:34
Hi @Abhra303,
Thanks for reporting this. As you mentioned in the issue, this was supposed to be fixed in #304.

As a workaround, you can use brew package manager to install datree as described here:
https://hub.datree.io/#a-1-install-datrees-cli-integration

To help us investigate, since it worked for our M1 processor, can you please share the output of the following commands:
`uname -m`
`uname -s`
`sysctl -n machdep.cpu.brand_string`

Thanks

**Comment by Abhra303** [comment] 2022-01-18 07:44
Hello @dimabru, I ran the commands as you said here is the output -

<img width="495" alt="Screenshot 2022-01-18 at 1 11 49 PM" src="https://user-images.githubusercontent.com/75240995/149892334-fecc3bd2-29d6-475b-886f-6c8955cf9bf3.png">

**Comment by dimabru** [comment] 2022-01-18 07:50
Thanks!
Adding some context here for a possible solution:

goreleaser can now support universal binaries (i.e arm64 and amd64 in the same executable): https://goreleaser.com/customization/universalbinaries
we can look into upgrading our goreleaser version to add that ability

**Comment by shmuelsa** [comment] 2022-01-18 11:42
Hey @Abhra303,

We added a new binary for Darwin-arm64 on our latest RC version [0.15.2-rc](https://github.com/datreeio/datree/releases/tag/0.15.2-rc) 
Please download and update if the problem is resolved.

[datree-cli_0.15.2-rc_Darwin_arm64.zip](https://github.com/datreeio/datree/releases/download/0.15.2-rc/datree-cli_0.15.2-rc_Darwin_arm64.zip)

**Comment by Abhra303** [comment] 2022-01-18 12:11
Thanks @shmuelsa 

It is finally working.

**Closed as completed** 2022-01-18 13:57 UTC
Labels: bug
