### ISSUE TITLE
Rule CRONJOB_INVALID_SCHEDULE_VALUE is incomplete

### ISSUE THREAD

**Issue by kedith** [datreeio/datree#711] opened 2022-07-06 12:20 UTC
**Describe the bug**
The [default rule #8](https://github.com/datreeio/datree/blob/38c5fb3cc5b89148f2edcdb49d8b9dd1aab17aaf/pkg/defaultRules/defaultRules.yaml#L256) is incomplete. I found a valid CronJob schedule pattern which isn't accepted by the rule.

**To Reproduce**
- Run the rule against a cronjob definition containing 00 on the first or second position (minute/hour) in the schedule. ex:
```yaml
schedule: "00 * * * *"
```

**Expected behavior**
The rule should also accept 00 for minute/hour, not just 0.

**Datree version (run `datree version`):**
 - Version:  1.5.20

**Additional context**  
I am trying to integrate datree in a project and it fails on a valid CronJob definition we have. This rule is useful and it would be great if the regex would be fixed.

**Comment by eyarz** [comment] 2022-07-07 05:58
good catch.
I updated the regex and put it on [regex101](https://regex101.com/r/zeBFF0/1).
@kedith before I'm opening a PR for this fix, can you help me verify the new (regex) pattern by testing some valid & invalid cron examples?
I want to verify it's not producing false positive/negative results.

**Comment by kedith** [comment] 2022-07-07 06:41
thanks @eyarz. 
I will try to test it with some values too.

**Comment by kedith** [comment] 2022-07-07 06:59
```* 00 * * *``` should be accepted by the regex as well.

**Comment by eyarz** [comment] 2022-07-07 11:00
oops...
@kedith  I [fixed the regex](https://regex101.com/r/Py2DcJ/1) and also added validation for `* * * * 00`, so please give it another try now.

If you are wondering why I missed all those `00` expressions is because it was not provided as an allowed value in the CRON expression definition 😅

![image](https://user-images.githubusercontent.com/19731161/177758113-b8e11ba5-d41a-4d1c-9b05-80a41e1b4b99.png)

**Comment by kedith** [comment] 2022-07-08 05:53
@eyarz  I [tested](https://regex101.com/r/ipfuMV/1) it with more values. It seems to pass on all my examples but I found some corner cases where it shouldn't pass but passes. I thought of testing ranges where the starting value is still valid but the upper range not, ex:
```* * * 12-14 *```, ```* * * * 5,8```

I found this website useful while thinking of valid/invalid patterns https://crontab.guru/

Thanks a lot for your fast responses and help 🙂

**Comment by eyarz** [comment] 2022-07-09 07:26
@kedith you are right, the regex didn't validate the range for the second set of numbers after `,` or `-` 🙈
I [updated the regex](https://regex101.com/r/2D5tTX/1), and I think we are ready now! 🤞

I'm familiar with crontab.guru, but the problem is that you can only generate random examples of **valid** cron expressions...

**Comment by kedith** [comment] 2022-07-11 05:29
Great! I don't have any other ideas for test cases. Thanks a lot @eyarz 🎉!

**Comment by eyarz** [comment] 2022-07-12 18:41
The rule logic was updated on will be fixed on the next CLI release.
@kedith it looks like we just created the first regex to validate cron statements so I also published it on [StackOverflow](https://stackoverflow.com/a/67419837/9595106) 🤓

**Closed as completed by eyarz** 2022-07-12 18:41 UTC
Labels: bug, WIP
