### ISSUE TITLE
Policy validation errors order is inconsistent between runs

### ISSUE THREAD

**Issue by royhadad** [datreeio/datree#580] opened 2022-04-20 10:12 UTC
**Describe the bug**
The order of the policy validation errors is inconsistent between runs, this makes checking for diffs & regressions confusing.

**To Reproduce**
1. Run command `datree test ~/.datree/k8s-demo.yaml`
2. Run command again `datree test ~/.datree/k8s-demo.yaml`
3. Most likely the order of the policy validation errors between the 2 runs is not the same. 
4. You may need try again in order to reproduce the bug because it seems to be random.

**Expected behavior**
Policy validation errors are the same order between runs

**Screenshots**
run #1
<img width="650" alt="Screen Shot 2022-04-20 at 13 06 31" src="https://user-images.githubusercontent.com/39004075/164204684-93688e9b-2a29-4d81-8a37-10a6c95ccfc7.png">

run #2
<img width="606" alt="Screen Shot 2022-04-20 at 13 06 21" src="https://user-images.githubusercontent.com/39004075/164204693-0ecde94b-85eb-4810-a343-d356bc7e74d5.png">

**Desktop (please complete the following information):**
 - OS: MacOS

**Datree version (run `datree version`):**
 - Version: 1.2.9

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: internal_rtv2ZXT8kjwwTPhTyvT5SY

**Additional context**  
This confused me mostly when using `--output json/yaml/xml/JUnit` and comparing diffs between runs

**suggested fix**
Simply sort the rule results before passing them down to the printer (for both `EvaluationResults` & `NonInteractiveEvaluationResults`)

**Comment by eyarz** [comment] 2022-04-20 10:55
@dimabru, If I remember correctly, this was the new behavior after we released the local eval support (1.x.x)?
If the fix is easy as you mentioned, I think we should do it.

**Comment by royhadad** [comment] 2022-04-20 16:08
@eyarz Yep I remember it also

**Comment by eyarz** [comment] 2022-04-20 17:25
so it's not a bug 😅

> If the fix is easy as you mentioned, I think we should do it.

**Comment by 406712774** [comment] 2022-04-20 21:06
Pues yo como nose k contestar Yano boy a contestar Anada mejor así

**Comment by TzlilSwimmer123** [comment] 2022-04-25 08:46
Fixed in https://github.com/datreeio/datree/pull/584

**Closed as completed by TzlilSwimmer123** 2022-04-25 08:46 UTC
Labels: bug
