### ISSUE TITLE
GitLab CI "datree kustomize test ..." --no-record flag is not working

### ISSUE THREAD

**Issue by hivl** [datreeio/datree#691] opened 2022-06-22 13:42 UTC
**Describe the bug**
I'm trying to run datree in gitlab ci job to check kustomize manifest with cliArgument '--no-record' and it is not working

**To Reproduce**
create gitlab-ci.yaml and try to run 'datree kustomize test /path/ --no-records

![datree](https://user-images.githubusercontent.com/1629464/175043122-b891d2f3-ebdb-42ca-9f57-3e804153f168.png)

**Comment by eyarz** [comment] 2022-06-22 13:49
from looking at the failure message, it looks like you just need to upgrade Datree to make it work correctly.
I guess you're using a deprecated version in your CI.

**Comment by eyarz** [comment] 2022-06-22 14:14
Also reproduces in my environment:
![image](https://user-images.githubusercontent.com/19731161/175049534-4cf183ce-3496-4abb-885f-4ee9d8329d95.png)
For the person that is taking this ticket - it is working as expected when not using `kustomize`.

@hivl this bug will be fixed soon, but FYI, not setting the token in your CI will also not connect it to **your policy**, which means you will always use the **default rules** in the policy you're running in your CI.

**Comment by royhadad** [comment] 2022-06-23 14:01
fixed in the latest release (1.5.17)

**Closed as completed by royhadad** 2022-06-23 14:01 UTC
Labels: bug, WIP
