### ISSUE TITLE
Replace yaml reader with the k8s yaml reader

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#377] opened 2022-01-17 14:02 UTC
**Describe the solution you'd like**
Since we scan Kubernetes manifests, it would be best practice to align our current reader package with the same YAML-reader Kubernetes use. 

**"How to" Suggestion**
Replace "gopkg.in/yaml.v3" with  “https://github.com/kubernetes-sigs/yaml” in `bl/files.go` -> `ExtractFilesConfigurations()` and use `YAMLToJSON` to extract Kubernetes configurations from the files in the given path.
Required knowledge: basic Golang.

**Describe alternatives you've considered**
This is the only YAML reader Kubernetes use, as far as I can tell. For [example](https://github.com/kubernetes/kubectl/blob/ce9f95af72bc760e7eaca946b593ec9f16de389f/pkg/cmd/version/version.go).

**Comment by amustaque97** [comment] 2022-01-17 21:26
I can take this up!

**Comment by noaabarki** [comment] 2022-01-17 22:23
Hi @amustaque97, sounds terrific 😎  Assigned to you. Feel free to reach out with any question here and also in our [Slack channel](https://datreecommunity.slack.com/archives/C02L0QB3YTC).

**Comment by amustaque97** [comment] 2022-01-31 10:11
Hi @dimabru , curious to know why we have opened this issue again? Are we facing any issue because of replacement?

**Comment by dimabru** [comment] 2022-01-31 10:11
The pr that was merged to fix this issue caused a bug in our cli.
Policy checks running on yaml files with multiple `---` failed to execute policy checks on some resources

**Comment by amustaque97** [comment] 2022-01-31 10:17
Thanks for the reply, could you please share an example of yaml file and the command typed. I will take a look.

**Comment by shalev007** [comment] 2022-01-31 10:45
Hey @amustaque97,
![Screen Shot 2022-01-31 at 12 42 25](https://user-images.githubusercontent.com/51760613/151779789-aa5eb04c-8bd6-4710-ac7e-2d11c2a4d480.png)

Adding an example with steps to reproduce:
1. checkout to `0.15.9-rc` - `git checkout 0.15.9-rc` (which is the version that this pr that closed this issue, was added)
2. run the following command `make build-staging && ./datree test examples/Security/fail.yaml`
3. look at the `Configs tested against policy` and see that it states 1 instead of 2

**Comment by amustaque97** [comment] 2022-01-31 13:05
Nice catch. I checked and found that `YAMLToJSON` is the culprit as it is not able to parse and return multiple yaml configs. 
Thank you everyone!

**Closed as completed** 2022-04-07 16:17 UTC
Labels: enhancement, good first issue, WIP, up for grabs
