### ISSUE TITLE
Add Datree as package in Scoop package manager for Windows users

### ISSUE THREAD

**Issue by pcgeek86** [datreeio/datree#799] opened 2022-09-15 20:36 UTC
**Is your feature request related to a problem? Please describe.**

- As a Windows user, I manage my dev tools using the Scoop command line package manager.
- I install other tools, such as `kubectl`, `meshery`, `kubeseal`, and others, using Scoop.
- I would like to install Datree CLI using Scoop package manager.

![image](https://user-images.githubusercontent.com/466713/190503930-78603a4e-5fb9-42c8-bd2f-fda81b3270ba.png)

**Describe the solution you'd like**

I would like Datree CLI distributed via Scoop package manager for Windows.

**Describe alternatives you've considered**

n/a

**Additional context**

- [ ] TODO: Create [Scoop package manifest](https://github.com/ScoopInstaller/Main) for Datree CLI.

**Comment by darkknight20032001** [comment] 2022-10-29 08:30
I am interested.

**Comment by adifayer** [comment] 2022-10-30 08:42
@darkknight20032001 Would you like to be assigned to this task? :)

**Comment by darkknight20032001** [comment] 2022-10-30 20:18
> @darkknight20032001 Would you like to be assigned to this task? :)

Yes please

**Comment by adifayer** [comment] 2022-11-02 12:30
@darkknight20032001 You got it ✨

**Comment by rakshitgondwal** [comment] 2022-12-22 14:39
Hey! @darkknight20032001. Are you still working on this?

**Comment by aamirpatel** [comment] 2023-02-17 06:39
hey! @darkknight20032001 would you like to assign me this task?

**Comment by adifayer** [comment] 2023-02-19 09:24
@aamirpatel the issue is up for grabs, feel free to assign yourself if you'd like that :)

**Comment by SarveshRansubhe** [comment] 2023-03-08 11:45
datree is now available on [scoop](https://github.com/ScoopInstaller/Main/pull/4525)

**Comment by eyarz** [comment] 2023-03-12 09:41
@SarveshRansubhe how can we also update the scoop version on every datree new release?
I'm afraid scoop users will not get the most up-to-date version in the future...

**Comment by SarveshRansubhe** [comment] 2023-03-12 13:12
They have bot which autoupdates as I have specified a "autoupdate" field there.

**Closed as completed** 2023-03-13 06:51 UTC
Labels: enhancement, good first issue, up for grabs
